### PR TITLE
Auto-detect HTML for properly setting textType parameter in AzureTranslator

### PR DESCRIPTION
**Pull request by adv12**
With this pull request, the AzureTranslator now has an option to auto-detect HTML in resource strings so it can set the "textType" parameter to "html".  It was defaulting to "plain", which allows the translator to munge or try to translate HTML tags.  Added a reference to HTML Agility Pack rather than relying on a busted Regex for identifying HTML tags.  Hope that's not too heavyweight of an addition.

### CODE REVIEW

**Comment by adv12** [comment]
I left in the 10-item limit per API call because I assumed there was some reasoning behind it.  FYI, Azure allows up to 100 items per request provided the total character count across all the Text fields doesn't exceed 5000.  If the purpose of the Take(10) in the original code was to avoid exceeding the character limit, the current code works better, and the <10 in the for loop could be changed to <100.  API documentation here:

https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits

**Comment by tom-englert** [comment]
I did a little code cleanup to increase readability. Can you do some testing?
I think the limit of 10 was a leftover of the 2.0 API, I changed it to 100.

**Comment by adv12** [comment]
I'll try to get some testing done tomorrow (Monday) evening, or during work if they let me.  (This was done during a hackathon that has since ended.)  Thanks for the code cleanup; I knew it looked ugly but didn't feel comfortable rearranging other than to make the necessary logic changes.

**Comment by adv12** [comment]
Tested, and everything seemed fine except that I started getting 429001 errors on a large project (see 
[ResxGenerator.zip](https://github.com/tom-englert/ResXResourceManager/files/4187016/ResxGenerator.zip)).  I added an optional characters-per-minute throttle to address this, based on the guidance in the request limits document (https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits).

Relevant quote:

> The hourly quota should be consumed evenly throughout the hour. For example, at the F0 tier limit of 2 million characters per hour, characters should be consumed no faster than roughly 33,300 characters per minute sliding window (2 million characters divided by 60 minutes).
>
> If you reach or surpass these limits, or send too large of a portion of the quota in a short period of time, you'll likely receive an out of quota response. There are no limits on concurrent requests.

I added UI, but I barely know WPF and it looks horrible.  I was hoping you'd be able to tidy it up quickly; I only have so much time for this at work.  If you don't have time, I'll try to mess around in my evenings later this week.

**Comment by adv12** [comment]
Oh, one comment about the name "SupportsHtml": Google supports HTML by default without a flag, which is why I named the variable "MustIndicateHtml".  Not a big deal, just FYI.

**Comment by tom-englert** [comment]
:+1: :smile:

**Comment by adv12** [comment]
Thanks!

**Pull request merged**
