### PR TITLE
Addition of Microsoft Terminology Service as translator and ignoring shortcut indicators

### PR DESCRIPTION
**Pull request by dahall**
Implementation of enhancements #92 (Adding Microsoft Terminology Service as translator) and #93 (Ignoring keyboard shortcut indicator ('&') in strings passed to Azure).

### CODE REVIEW

**Comment by dahall** [comment]
I've also completed the work on the Google Translator.

**Comment by tom-englert** [comment]
:+1: 
@dahall shouldn't the keyboard shortcut indicator be ignored for all translators?

**Comment by dahall** [comment]
I would think so, except for the new Microsoft Terminology service which actually uses them to return results with keyboard shortcuts. I added it to Azure and Google already.

**Comment by tom-englert** [comment]
OK, I added it to MyMemory, too.

**Comment by dahall** [comment]
One other note. The Google translation service does not provide a quality metric with their translations. I set the default to 1.0. If you think it should be something lower, you should change it before releasing.

**Comment by dahall** [comment]
Having used Google Translate before I can't say that I feel like all of their translations are perfect. I went back and forth on that default metric. I think maybe 0.8 might be more accurate.

**Comment by tom-englert** [comment]
I think, that's OK.

**Pull request merged**
